[package]
name = "sw_auth"
version = "0.1.0"
edition = "2021"
description = "Authentication API for Script-Ware M Auth"
license = "MIT"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.0"
regex = "1.7.3"
